// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	date "google.golang.org/genproto/googleapis/type/date"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32     `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Gender               Gender     `protobuf:"varint,4,opt,name=gender,proto3,enum=user.Gender" json:"gender,omitempty"`
	Birthday             *date.Date `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday,omitempty"`
	CreatedAt            *date.Date `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *date.Date `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            *date.Date `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

func (m *User) GetBirthday() *date.Date {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *User) GetCreatedAt() *date.Date {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *date.Date {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetDeletedAt() *date.Date {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Users)(nil), "user.Users")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74) }

var fileDescriptor_ed89022014131a74 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x99, 0x34, 0xfd, 0xbb, 0xd5, 0x6a, 0x67, 0x51, 0x86, 0xb8, 0x19, 0x8a, 0x8b, 0x88,
	0x74, 0x22, 0xf1, 0x09, 0x0a, 0x8a, 0xfb, 0x88, 0x6b, 0x99, 0x76, 0xae, 0x31, 0xd0, 0x36, 0x61,
	0x32, 0x15, 0xfa, 0x44, 0xbe, 0xa6, 0xcc, 0x4f, 0xa4, 0x9b, 0x6c, 0xc2, 0xbd, 0xe7, 0x9c, 0x2f,
	0x39, 0x93, 0x81, 0x9b, 0x53, 0x8b, 0x3a, 0xb3, 0x0f, 0xd1, 0xe8, 0xda, 0xd4, 0x34, 0xb6, 0x73,
	0xb2, 0x70, 0x72, 0x89, 0x47, 0xd5, 0x19, 0xc9, 0x5d, 0x59, 0xd7, 0xe5, 0x1e, 0x33, 0xb7, 0x6d,
	0x4f, 0x5f, 0x19, 0x1e, 0x1a, 0x73, 0x0e, 0xe6, 0x32, 0x98, 0xe6, 0xdc, 0x60, 0xa6, 0xa4, 0x41,
	0xaf, 0xaf, 0x7e, 0x23, 0x88, 0x3f, 0x5a, 0xd4, 0x74, 0x0e, 0x51, 0xa5, 0x18, 0xe1, 0x24, 0x9d,
	0x16, 0x51, 0xa5, 0x28, 0x85, 0xf8, 0x28, 0x0f, 0xc8, 0x22, 0xa7, 0xb8, 0x99, 0xde, 0xc2, 0x40,
	0x96, 0xc8, 0x06, 0x9c, 0xa4, 0xd7, 0x85, 0x1d, 0xe9, 0x3d, 0x8c, 0x7c, 0x07, 0x16, 0x73, 0x92,
	0xce, 0xf3, 0x2b, 0xe1, 0x9a, 0xbe, 0x39, 0xad, 0x08, 0x1e, 0x5d, 0xc3, 0x64, 0x5b, 0x69, 0xf3,
	0xad, 0xe4, 0x99, 0x0d, 0x39, 0x49, 0x67, 0xf9, 0x42, 0xf8, 0x3e, 0xc2, 0xf6, 0x11, 0x2f, 0xd2,
	0x60, 0xf1, 0x1f, 0xa1, 0x4f, 0x00, 0x3b, 0x8d, 0xd2, 0xa0, 0xfa, 0x94, 0x86, 0x8d, 0xfa, 0x80,
	0x69, 0x08, 0x6d, 0x8c, 0x25, 0x4e, 0x8d, 0xea, 0x88, 0x71, 0x2f, 0x11, 0x42, 0x9e, 0x50, 0xb8,
	0xc7, 0x40, 0x4c, 0x7a, 0x89, 0x10, 0xda, 0x98, 0xd5, 0x03, 0x0c, 0xed, 0x8f, 0x6a, 0x29, 0x87,
	0xa1, 0x3d, 0x64, 0xcb, 0x08, 0x1f, 0xa4, 0xb3, 0x1c, 0xfc, 0x91, 0xad, 0x57, 0x78, 0x23, 0xaf,
	0x60, 0x66, 0xd7, 0x77, 0xd4, 0x3f, 0xd5, 0x0e, 0xe9, 0x63, 0x47, 0x2e, 0xbb, 0x0f, 0x74, 0x57,
	0x24, 0x5e, 0xed, 0x15, 0x25, 0x17, 0xaf, 0xa0, 0x6b, 0x18, 0x6f, 0x94, 0x72, 0xe3, 0x85, 0x9c,
	0xf4, 0xa0, 0xdb, 0x91, 0xdb, 0x9f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xe1, 0x08, 0xe3,
	0x27, 0x02, 0x00, 0x00,
}
